### ISSUE TITLE
Add a -cmake switch to create a CMakeLists.txt file

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttBld#230]
### Description:
The impetus for creating **ttBld** in the first place was after I spent hours and hours trying to get cmake configured enough to be able to build a very simple project. However, for people who are used to working with cmake and therefore prefer that method, we should at least create a skeleton **CMakeLists.txt** that utilizes many of the options specified in .srcfiles. This would be a one-time generation, not an auto-generation like the .ninja files -- so if the file already exists, we should NOT overwrite it.

**Comment by KeyWorksRW** [comment]
We've recently added the ability to generate a valid 2019 Visual Studio project. It would make sense now to also generate a valid **cmake** project which would probably be preferred over the VS project file.

**Comment by Randalphwa** [comment]
Version 3.17 of **cmake** added a `Ninja Multi-Config` generator. Prior to that, one major advantage of the **ttBld** generated ninja scripts was the multi-target support. **ttBld** sill has an advantage of making it easy to build with either `msvc` or `clang-cl.exe` without needing different build directories. For small projects, even running nmake on the **ttBld**-generated `makefile`, builds are faster then the cmake-generated ninja scropts. However, once you have enough source files that the cmake-generated overhead is no longer a major factor, the two systems _should_ be at least similar in build performance.

Note that using .srcfiles.yaml to create a CMakeLists.txt file would also make it possible to import a **Visual Studio** project file and output a **cmake** project. 😃
