### ISSUE TITLE
Use /FI to force include precompiled header file

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttBld#334]
### Description:

CMake creates a temporary header file and force-includes it in every source file, eliminating the need to have a `#include "pch.h"` line in every source file. If our ninja scripts also used this option (/FI for msvc/clang-cl) then we could eliminate the precompiled header line in all source files.

**Comment by Randalphwa** [comment]
It certainly looks weird to not have the precompiled header file specified in a source file, however it does provide a couple of advantages:

- The file isn't included twice by CMake builds requiring #pragma once in the precompiled header file
- It can be used in projects such as wxWidgets samples that don't specify a precompiled header
- It can override an existing precompiled header such as `wx/wxprec.h` allowing the user to create a more efficient or customized precompiled header
