### ISSUE TITLE
Add support for BuildLibs in -cmake command

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttBld#335]
### Description:

It's quite a bit of guesswork to switch a project that uses BuildLibs to build ttlib.lib to figuring out which source files to compile. That's fine for our bigger projects like **wxUiEditor**, but quite a pain for the smaller projects.

**Comment by Randalphwa** [comment]
Unfortunately, this isn't going to work. There's simply too many ways to build a library such as which precompiled header file to use, whether to use the same or different include directories, etc. **BuildLibs** was designed to run ninja in an entirely different directory, and that doesn't necessarily make sense with a CMake build system.
